title: Michael Dunst # your name (or website title) here
logo: "/images/circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Pennsylvania Master of City Planning student 
  <br><br>
  Passionate about and skilled in transportation planning, real estate development, and creating livable cities. 
  <br><br>
  <a href="https://www.linkedin.com/in/michael-dunst/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://docs.google.com/document/d/1_-Z8mO7TpNOJU-D1FP8Vc1ED3lGxpgqGMKX5T2IxZKA/edit?usp=sharing">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
